In [1]:
# 测试下tensorflow模块是否正常
import tensorflow as tf
hello = tf.constant('Hello Mike.')
sess = tf.Session()
print(sess.run(hello))

b'Hello Mike.'


In [2]:
# tesorflow使用的计算图
a = tf.constant(2,tf.int16)
b = tf.constant(2,tf.int32)
graph = tf.Graph()
with graph.as_default():
    a = tf.Variable(8, tf.float32)
    b = tf.Variable(tf.zeros([2,2], tf.float32))
    
with tf.Session(graph=graph) as session:
    tf.global_variables_initializer().run()
    print(session.run(a))
    print(session.run(b))

8
[[ 0.  0.]
 [ 0.  0.]]


In [4]:
w1 = tf.Variable(tf.random_normal([1,2],stddev=1,seed=1))

# 因为需要重复输入x，而每建一个x就会生成一个结点，计算图的效率会低。所以使用占位符placeholder
x = tf.placeholder(tf.float32,shape=(1,2))
x1 = tf.constant([[0.7,0.9]])

a = x + w1
b = x1 + w1

sess = tf.Session()
sess.run(tf.global_variables_initializer())

# 运行y时将占位符填上，feed_dict为字典，变量名不可变
y_1 = sess.run(a,feed_dict={x:[[0.7,0.9]]})
y_2 = sess.run(b)
print(y_1)
print(y_2)
sess.close


[[-0.11131823  2.38459873]]
[[-0.11131823  2.38459873]]


<bound method BaseSession.close of <tensorflow.python.client.session.Session object at 0x10734ec18>>

In [6]:
import numpy as np

list_of_points1_ = [[1,2], [3,4], [5,6], [7,8]]
list_of_points2_ = [[15,16], [13,14], [11,12], [9,10]]

list_of_points1 = np.array([np.array(elem).reshape(1,2) for elem in list_of_points1_])
list_of_points2 = np.array([np.array(elem).reshape(1,2) for elem in list_of_points2_])

graph = tf.Graph()

with graph.as_default():   

    # 我们使用 tf.placeholder() 创建占位符 ，在 session.run() 过程中再投递数据 
    point1 = tf.placeholder(tf.float32, shape=(1, 2))
    point2 = tf.placeholder(tf.float32, shape=(1, 2))
    # 计算两点间欧式距离
    def calculate_eucledian_distance(point1, point2):
        difference = tf.subtract(point1, point2)
        power2 = tf.pow(difference, tf.constant(2.0, shape=(1,2)))
        add = tf.reduce_sum(power2)
        eucledian_distance = tf.sqrt(add)
        return eucledian_distance

    dist = calculate_eucledian_distance(point1, point2)

with tf.Session(graph = graph) as session:  # graph=graph ???
    tf.global_variables_initializer().run()   
    for ii in range(len(list_of_points1)):
        point1_ = list_of_points1[ii]
        point2_ = list_of_points2[ii]

        # 使用feed_dict将数据投入到[dist]中
        feed_dict = {point1 : point1_, point2 : point2_}
        distance = session.run([dist], feed_dict=feed_dict)
        print("the distance between {} and {} -> {}".format(point1_, point2_, distance))


the distance between [[1 2]] and [[15 16]] -> [19.79899]
the distance between [[3 4]] and [[13 14]] -> [14.142136]
the distance between [[5 6]] and [[11 12]] -> [8.485281]
the distance between [[7 8]] and [[ 9 10]] -> [2.8284271]
