In [3]:
# 构建三层全连接神经网络
import tensorflow as tf
from numpy.random import RandomState

batch_size = 10
# 设置 batch_size参考：
# https://www.zhihu.com/question/32673260/answer/71137399

w1 = tf.Variable(tf.random_normal([2,3],stddev=1,seed=1))
w2 = tf.Variable(tf.random_normal([3,1],stddev=1,seed=1))

# None 可以根据batch 大小确定维度，在shape的一个维度上使用None
x = tf.placeholder(tf.float32,shape=(None,2))
y = tf.placeholder(tf.float32,shape=(None,1))

# activate function 使用ReLU
a = tf.nn.relu(tf.matmul(x,w1))
yhat = tf.nn.relu(tf.matmul(a,w2))

# 定义交叉熵为损失函数，训练过程使用Adam算法最小化交叉熵
cross_entropy = -tf.reduce_mean(y*tf.log(tf.clip_by_value(yhat,1e-10,1.0))) # About gradient cliping
train_step = tf.train.AdamOptimizer(0.001).minimize(cross_entropy)

rdm = RandomState(1) # 返回一个一维随机数组
data_size = 512

# 生成两个特征，共data_size个样本
X = rdm.rand(data_size,2)
# 定义规则给出样本标签，所有 x1+x2<1 的样本认为是正样本，其他为负样本。Y，1为正样本
Y = [[int(x1+x2 < 1)] for (x1, x2) in X]

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(w1))
    print(sess.run(w2))
    steps=11000
    for i in range(steps):
        # 选定每一个批量读取的首尾位置，确保在1个epoch内采样训练
        start = i * batch_size % data_size
        end = min(start + batch_size,data_size)
        sess.run(train_step,feed_dict={x:X[start:end],y:Y[start:end]})
        if i % 1000 == 0:
            training_loss= sess.run(cross_entropy,feed_dict={x:X,y:Y})
            print("在迭代 %d 次后，训练损失为 %g"%(i,training_loss))

[[-0.81131822  1.48459876  0.06532937]
 [-2.44270396  0.0992484   0.59122431]]
[[-0.81131822]
 [ 1.48459876]
 [ 0.06532937]]
在迭代 0 次后，训练损失为 0.308504
在迭代 1000 次后，训练损失为 0.0393406
在迭代 2000 次后，训练损失为 0.0182158
在迭代 3000 次后，训练损失为 0.0104779
在迭代 4000 次后，训练损失为 0.00680374
在迭代 5000 次后，训练损失为 0.00446512
在迭代 6000 次后，训练损失为 0.00296797
在迭代 7000 次后，训练损失为 0.00218553
在迭代 8000 次后，训练损失为 0.00179452
在迭代 9000 次后，训练损失为 0.0013211
在迭代 10000 次后，训练损失为 0.000957699
